# Generated by Django 5.2.7 on 2025-10-08 08:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberapp', '0002_alter_payment_amount_alter_payment_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='idnumber',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='UsageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyberapp.student')),
            ],
        ),
    ]
