# Generated by Django 5.2.7 on 2025-11-15 18:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberapp', '0003_alter_student_idnumber_usagesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagesession',
            name='amount_charged',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='usagesession',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usagesession',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usagesession',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='usagesession',
            name='payment_status',
            field=models.CharField(choices=[('not_requested', 'Not requested'), ('awaiting_payment', 'Awaiting payment'), ('pending', 'Pending confirmation'), ('paid', 'Paid'), ('failed', 'Failed')], default='not_requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
