# Generated by Django 5.2.7 on 2025-11-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberapp', '0004_usagesession_amount_charged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_status',
            field=models.CharField(choices=[('not_requested', 'Not requested'), ('pending', 'Pending confirmation'), ('paid', 'Paid'), ('failed', 'Failed')], default='not_requested', max_length=20),
        ),
    ]
